/*
  action types
*/

const user = {
  SET_USER_NAME: 'SET_USER_NAME',
  SET_USER_AVATAR: 'SET_USER_AVATAR',
  USER_START_AUTHORIZING: 'USER_START_AUTHORIZING',
  USER_AUTHORIZED: 'USER_AUTHORIZED',
  USER_NO_EXIST: 'USER_NO_EXIST'
}

export default user
